### ISSUE TITLE
Modules still export reactPanel instead of plugin

### ISSUE THREAD

**Issue by vrunda-thacker** [grafana/react-plugin-examples#2]
The module.tsx for all 3 panels is returning 'reactPanel', where as Grafana is expecting plugin.
Please refer to this from 'grafana/public/app/features/plugins/plugin_loader.ts' -
```
return importPluginModule(meta.module)
    .then(pluginExports => {
      if (pluginExports.plugin) {
        return pluginExports.plugin as PanelPlugin;
      } else if (pluginExports.PanelCtrl) {
        const plugin = new PanelPlugin(null);
        plugin.angularPanelCtrl = pluginExports.PanelCtrl;
        return plugin;
      }
      throw new Error('missing export: plugin or PanelCtrl');
    })
```

The change that is required is very simple: Rename the exported variable from 'reactPanel' to 'plugin' in all three panels.

**Comment by neosarchizo** [comment]
@vrunda-thacker Can you fix it on your own? I also have a same problem. But I can't fix it on my own.
